### ISSUE TITLE
SMILES Parse Error after first active learning iteration

### ISSUE THREAD

**Issue by sonjakatz** [batistagroup/ChemSpaceAL#7] opened 2024-07-18 09:38 UTC
We continuously run into errors when trying to sample from the latent space and generate SMILES for scoring. 

After downloading the provided pre-trained models SMILE generation and the rest of the workflow runs without errors; after active learning (for 10 epochs) however, it seems only corrupted SMILES are generated (see error message below). 

In the end, only a single SMILE with very low scores (~2) passed the filtering. We are trying to replicate the published work so no other settings were altered.

Anyone runs into similar issues? 

* * *

Error message: 
`
(...)
[18:05:37] SMILES Parse Error: Failed parsing SMILES 'Cl<)1C)4(C()' for input: 'Cl<)1C)4(C()'
[18:05:37] SMILES Parse Error: syntax error while parsing: )o
[18:05:37] SMILES Parse Error: Failed parsing SMILES ')o' for input: ')o'
[18:05:37] SMILES Parse Error: unclosed ring for input: '[C@@H]3-cccnC(=N)CC1=222cCc-N'
[18:05:37] SMILES Parse Error: syntax error while parsing: [C@H]O31OClC[C@H]<OClc3-3!)cC1=!43=
[18:05:37] SMILES Parse Error: Failed parsing SMILES '[C@H]O31OClC[C@H]<OClc3-3!)cC1=!43=' for input: '[C@H]O31OClC[C@H]<OClc3-3!)cC1=!43='
[18:05:37] SMILES Parse Error: syntax error while parsing: 1=c
[18:05:37] SMILES Parse Error: Failed parsing SMILES '1=c' for input: '1=c'
[18:05:37] SMILES Parse Error: syntax error while parsing: 1<)3C3
[18:05:37] SMILES Parse Error: Failed parsing SMILES '1<)3C3' for input: '1<)3C3'
[18:05:37] SMILES Parse Error: unclosed ring for input: 'S[C@@H]4'
[18:05:37] SMILES Parse Error: syntax error while parsing: 3c
[18:05:37] SMILES Parse Error: Failed parsing SMILES '3c' for input: '3c'
[18:05:37] SMILES Parse Error: syntax error while parsing: C24c4-[C@H]<<c
[18:05:37] SMILES Parse Error: Failed parsing SMILES 'C24c4-[C@H]<<c' for input: 'C24c4-[C@H]<<c'
[18:05:37] SMILES Parse Error: unclosed ring for input: 'C[C@H]-CN=3Cl'
[18:05:37] SMILES Parse Error: syntax error while parsing: 2cC[C@H]n12()n2[C@H]<(C<C=-on2
[18:05:37] SMILES Parse Error: Failed parsing SMILES '2cC[C@H]n12()n2[C@H]<(C<C=-on2' for input: '2cC[C@H]n12()n2[C@H]<(C<C=-on2'
[18:05:37] SMILES Parse Error: extra close parentheses while parsing: CS)
[18:05:37] SMILES Parse Error: Failed parsing SMILES 'CS)' for input: 'CS)'
[18:05:37] SMILES Parse Error: syntax error while parsing: S32S-S(=)3
[18:05:37] SMILES Parse Error: Failed parsing SMILES 'S32S-S(=)3' for input: 'S32S-S(=)3'
[18:05:37] SMILES Parse Error: syntax error while parsing: <-4cc[C@@H]onC1<-S-c41nC!ccCl[C@@H])!
[18:05:37] SMILES Parse Error: Failed parsing SMILES '<-4cc[C@@H]onC1<-S-c41nC!ccCl[C@@H])!' for input: '<-4cc[C@@H]onC1<-S-c41nC!ccCl[C@@H])!'
(...)
`

**Comment by anmorgunov** [comment] 2024-07-18 15:54
Some SMILES parse errors are expected as even with 99% validity for 100k generations there'll be ~1000 invalid molecules. But there should be way more than a single smile after 1 round of AL. Do you mind sharing the scores for the 1000 docked molecules? It should be saved as a .csv to 4_Scoring/scored_dataframes. 

We did a few code quality improvements after production runs before publication, so it could be that we broke some things during that refactoring. I'll start one round of AL with the current notebook and get back to you with the results

**Comment by Kcomassi** [comment] 2024-07-22 12:44
I actually work together with the previous commentator and an error occurs when trying to sample from the generated smiles (untouched, only the 'target_number'. It seems the problem is that it doesnt sample from the generated smiles, so the sampled.csv needed for the next step is not created. It did work when just leaving the settings like they were in the colab (target_number=1). Like mentioned before, we are trying to replicate what you did so i want to keep it the same as much as possible, what settings were used to run it, and is the current colab working? because we couldnt get past the pretraining step. If there is an updated version could we get that?

**Comment by anmorgunov** [comment] 2024-07-22 21:40
I started testing the notebook in a fresh directory from a clean slate. Using the notebook provided in the repo, I only change base_path (in what is now Cell 3, I added cell numbers), and update "cycle_prefix" in Cell 5 to be "model7" because that's what corresponds to the model checkpoint you can download using Cell 4. Because it's a generation from pretrained model, I also set `al_iteration=0`. I set `target_number=100_000` in Cell 9 and run Cell 10, which generates 100k mols. Please let me know if you don't get to this point.

I then try to do sampling, and I get an error on Cell 13 stating that some descriptors are NaNs. As it turns out, we uploaded the raw scaler/pca file that included descriptors which we ultimately excluded from the production runs. I've uploaded the correct file, which is named "scaler_pca_combined_n120_v2.pkl". I've updated the notebook to reflect this change. After this correction, the notebook works up to sampling (I tried sampling 100 and 1000 mols). Please let me know if you don't get to this point.

I'm checking the docking part now, and it seems there are a few issues caused by updates in the Colab environment. I'll update you once I have a resolution to that.

> If there is an updated version could we get that?

As I said in my previous response, there was a jupyter notebook which we used to produce results used in the paper, and then we took that notebook and refactored code into a package. In that process, some things may have been transferred incorrectly (even though we tried to minimize the probability of that happening). I'm more than willing to provide the version of the notebook we used for our runs, but I'm afraid the code quality of that notebook is too bad to be comprehensible by anyone other than who wrote that code.

I'm somewhat confident that the current version of the notebook is correct for pretraining, generation, sampling, scoring, and AL training set construction. When we tested the notebook, we haven't re-run Docking (because it's expensive), we just pointed the function to existing poses and ensured that scoring/AL construction is correct. I'm currently re-running Docking to make sure it works, and I'll get back to you as soon as I have some results (but that may take awhile as I'm doing this after working hours in my free time)

**Comment by anmorgunov** [comment] 2024-07-22 23:10
Ok, a small update, Docking seems to work, I'm currently running it on 1000 mols. I'll merge #9 once I finish going through the whole AL iteration.

In the meantime, please do let me know if you can successfully generate & sample molecules. If you want to start docking before #9 is merged, change this line in Cell 1:
```bash
!git clone --single-branch --branch main https://github.com/batistagroup/ChemSpaceAL
```
Into
```bash
!git clone --single-branch --branch notebook-dev https://github.com/batistagroup/ChemSpaceAL
```

**Comment by Kcomassi** [comment] 2024-07-23 11:47
Thank you for your fast response! I am happy to say that the generation of SMILES, as well as the sampling works now. I am currently running the docking for the 1000 mols as well. I would be happy to hear from you if the rest of the Active learning also works and what i should change for the next iteration to get multiple iterations going.

**Comment by anmorgunov** [comment] 2024-07-23 20:30
I've merged #9. Check out [extended recipe in the README](https://github.com/batistagroup/ChemSpaceAL/tree/main?tab=readme-ov-file#running-the-notebook). 

Let me know if you have any issues. I'll close this issue by the end of this week otherwise

**Comment by Kcomassi** [comment] 2024-07-31 12:31
For me it seems like the first real iteration/next iteration , the generation of SMILES doesnt work well. Did it work for you?

**Comment by anmorgunov** [comment] 2024-07-31 15:39
What do you mean by "doesn't work well"? I reproduced pretty much the same metrics as from the original runs

**Comment by Kcomassi** [comment] 2024-07-31 18:22
For me following the exact steps, step 23 saves model weights to ; model weights will be saved to:               5_ActiveLearning/model_weights/model0_al1_ch1.pt, then after running the config for the next iteration, before generating new molecules the weights are loaded from 'model weights will be loaded from:            1_Pretraining/model_weights/model0_al1_ch1.pt'. I think the issue might arise from here somewhere.

**Comment by anmorgunov** [comment] 2024-07-31 18:28
the `mode` argument to `config.set_training_parameters` controls whether weights are loaded from `1_Pretraining/model_weights` or `5_ActiveLearning/model_weights`.

or you could have simply moved the file to wherever the model expects it

**Comment by anmorgunov** [comment] 2024-07-31 19:07
no, it took me an hour to run that cell with L4 on colab, which is a bit faster than on prev iteration because now the model is a bit better aligned to mols that pass the filter checks. 

i'd double check to ensure you're running on GPU

**Comment by anmorgunov** [comment] 2024-08-01 21:33
i'm going to close this one, but please feel free to start new issues if you have any troubles running / understanding the code

**Closed as completed by anmorgunov** 2024-08-01 21:33 UTC
Labels: bug, question
